# netlify.toml
# 终极暴力强装依赖版

[build]
  # 【核心修复】：强制 Netlify 在构建前必须老老实实执行 npm install 安装最外层的 node-appwrite
  command = "npm install && npm run docs:manifest"
  # 保持你网页的根目录
  publish = "/"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "APPWRITE_COLLECTION_USERS,APPWRITE_ENDPOINT"

[functions]
  directory = "netlify/functions"

[functions.js]
  node_version = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# 防止静态路由刷新 404
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
